---
title: "Mid-Project Update"
output: pdf_document
date: "2024-11-22"
---

EEB313: Mid-Project Update 

Yunjung Jo (1008751138), Victoria Cordova-Morote (1006907493), Andrew Batmunkh (1007610257)

	The data we will be using comes from big brown bat capture records from 1990-2010. The dataset contains 30,497 individual records across 3,797 unique capture sites, collected by wildlife agencies and researchers in the eastern United States. The data collection occurred within the months of March and October, when bats are not in hibernation, and recorded age, sex, reproductive status, mass, and forearm length. This data was paired with the spatiotemporal data of the pathogenic fungus Pseudogymnoascus destructans (Pd), which leads to white-nose syndrome in big brown bats when infected. While the infection status of each bat was not recorded, the period post-invasion was divided into the following stages depending on the number of years after introduction of the pathogen: invasion (0-1 years), epidemic (2-4 years), and established (5+ years).

	With this information, we initially hypothesized that bats captured during the later stages of pathogen invasion (epidemic and invasion periods) will have lower body mass and forearm length (‘fa’) due to the effects of the disease compared to bats captured before the invasion (pre-invasion) or during its early stages. However, after a more thorough look into the original study, we have decided to shift the direction of our project to using generalized linear models to find the predictors that best account for the response, which will be measured by change in mass. Pd infects the epithelial tissues of bat wings and muzzles during winter hibernation, causing increased water loss through evaporation, higher metabolic rates, and a resulting energy imbalance that can lead to starvation. These effects most likely have a direct effect on mass. Hence, the change in mass of the big brown bats will be our response.

  The original study hypothesized that “average mass and mass variation would decrease over Pd exposure time, with declines in mass and mass variation increasing with latitude”. The authors started off by differentiating the data based on sex, then plotted mass and mass difference from north to south for each sex. Female data were further faceted by reproductive status. For our project, we will attempt to group variables by different combinations and test which combination of variables best account for significant differences in mass using GLM. We are expanding on the original study, taking into account more variables and looking for potential interactions between the variables. Our null hypothesis is that the original model is the optimal model. Our alternative hypothesis is that there is a more suitable model for the change in mass of big brown bats.

  We have started off by making a histogram of the log mass of the bats, which was normally distributed. So far we have attempted to visualize the log mass of the bats pre- and post-invasion using scatter plots and violin plots, splitting up the data by different variables including age, sex, and reproductive status (simplified to pregnant or non-pregnant).

  Based on the data and visualizations of log(mass) by disease group, sex, age, and pregnancy status, we used the Generalized Linear Model (GLM) because of the continuous response variable with categorical predictors and interactions.

  The first GLM test model for sex showed that pre-invasion status increased log(mass) by 0.024 (p < 0.001), while males had a 0.154 decrease in log(mass) (p < 0.001). However, the interaction between invasion status and sex was not significant (p = 0.108).

  For age, pre-invasion status increased log(mass) by 0.012 (p < 0.001), and juveniles had a 0.187 lower log(mass) (p < 0.001). A significant interaction (p < 0.001) suggested invasion effects differed between adults and juveniles. For pregnancy, both Pre-Invasion and pregnancy status significantly increased log(mass) (p < 0.001), but their interaction was not significant (p = 0.065). Overall, the models fit well, showing low AIC values and residual deviation, highlighting significant effects of invasion, age, sex, and pregnancy on log(mass). We will continue to explore the data, attempting more combinations between the predictors.
